# Generated by Django 5.2.5 on 2025-11-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('issuer', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('url', models.URLField(blank=True)),
                ('icon_class', models.CharField(default='fas fa-certificate', help_text='FontAwesome icon class', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='education',
            name='icon_class',
            field=models.CharField(default='fas fa-graduation-cap', help_text='FontAwesome icon class', max_length=50),
        ),
        migrations.AddField(
            model_name='experience',
            name='icon_class',
            field=models.CharField(default='fas fa-briefcase', help_text='FontAwesome icon class', max_length=50),
        ),
    ]
