# Generated by Django 5.2.5 on 2025-11-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_certification_education_icon_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='experience',
            name='use_logo',
            field=models.BooleanField(default=False, help_text='Check to use the uploaded logo instead of the icon'),
        ),
    ]
