# Generated by Django 5.2.5 on 2025-11-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_experience_company_logo_experience_use_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='institution_logo',
            field=models.ImageField(blank=True, null=True, upload_to='institution_logos/'),
        ),
        migrations.AddField(
            model_name='education',
            name='use_logo',
            field=models.BooleanField(default=False, help_text='Check to use the uploaded logo instead of the icon'),
        ),
    ]
