# Generated by Django 5.2.5 on 2025-11-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_education_institution_logo_education_use_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='certification_logo',
            field=models.ImageField(blank=True, null=True, upload_to='certification_logos/'),
        ),
        migrations.AddField(
            model_name='certification',
            name='use_logo',
            field=models.BooleanField(default=False, help_text='Check to use the uploaded logo instead of the icon'),
        ),
    ]
